require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/common_employee_projects", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # CommonEmployeeProject. As you add validations to CommonEmployeeProject, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CommonEmployeeProject.create! valid_attributes
      get common_employee_projects_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      common_employee_project = CommonEmployeeProject.create! valid_attributes
      get common_employee_project_url(common_employee_project)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_common_employee_project_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      common_employee_project = CommonEmployeeProject.create! valid_attributes
      get edit_common_employee_project_url(common_employee_project)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CommonEmployeeProject" do
        expect {
          post common_employee_projects_url, params: { common_employee_project: valid_attributes }
        }.to change(CommonEmployeeProject, :count).by(1)
      end

      it "redirects to the created common_employee_project" do
        post common_employee_projects_url, params: { common_employee_project: valid_attributes }
        expect(response).to redirect_to(common_employee_project_url(CommonEmployeeProject.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CommonEmployeeProject" do
        expect {
          post common_employee_projects_url, params: { common_employee_project: invalid_attributes }
        }.to change(CommonEmployeeProject, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post common_employee_projects_url, params: { common_employee_project: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested common_employee_project" do
        common_employee_project = CommonEmployeeProject.create! valid_attributes
        patch common_employee_project_url(common_employee_project), params: { common_employee_project: new_attributes }
        common_employee_project.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the common_employee_project" do
        common_employee_project = CommonEmployeeProject.create! valid_attributes
        patch common_employee_project_url(common_employee_project), params: { common_employee_project: new_attributes }
        common_employee_project.reload
        expect(response).to redirect_to(common_employee_project_url(common_employee_project))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        common_employee_project = CommonEmployeeProject.create! valid_attributes
        patch common_employee_project_url(common_employee_project), params: { common_employee_project: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested common_employee_project" do
      common_employee_project = CommonEmployeeProject.create! valid_attributes
      expect {
        delete common_employee_project_url(common_employee_project)
      }.to change(CommonEmployeeProject, :count).by(-1)
    end

    it "redirects to the common_employee_projects list" do
      common_employee_project = CommonEmployeeProject.create! valid_attributes
      delete common_employee_project_url(common_employee_project)
      expect(response).to redirect_to(common_employee_projects_url)
    end
  end
end
